// <auto-generated />
namespace SincolPDV.Repositorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adicionandoUsuario_1_1_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicionandoUsuario_1_1_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201607131230357_adicionandoUsuario_1_1_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
